### ISSUE TITLE
Fastcall confusion

### ISSUE THREAD

**Issue by Romoku** [JLospinoso/jlospinoso.github.io#1]
On [your article](https://github.com/JLospinoso/jlospinoso.github.io/blob/master/_posts/2015-04-04-common-x86-calling-conventions.md)

You mention

>
    GLOBAL @MyFastcall@12
    EXPORT @MyFastcall@12
    @MyFastcall@12:
        xor eax,eax
        add eax,ecx
        add eax,edx
        add eax,[esp+4]
        ret 4
Notice that we must only **clean 4 bytes from the stack**, since two of our arguments are in registers rather than the stack. The naming convention for fastcall functions is to prepend an @, append an @, then **append the number of bytes to clean from the stack**.

I noticed that you named the function `@MyFastcall@12`. Should this be `@MyFastcall@4`?

**Comment by JLospinoso** [comment]
Hey! So the convention is to include the two arguments from the registers in the count, i.e. the number is not the amount of bytes cleaned off the stack. You can verify this by attempting to link the project with the following modification:

>
    GLOBAL @MyFastcall@4
    EXPORT @MyFastcall@4
    @MyFastcall@4:
        xor eax,eax
        add eax,ecx
        add eax,edx
        add eax,[esp+4]
        ret 4

And observe this linker error:

	Error	1	error LNK2019: unresolved external symbol @MyFastcall@12 referenced in function "public: void __thiscall CallingConventionsTest::MyFastcallTest::MyFastcallAddsCorrectly(void)" (?MyFastcallAddsCorrectly@MyFastcallTest@CallingConventionsTest@@QAEXXZ)	C:\Users\jalospinoso\Documents\casm-book\code\CallingConventionsTest\CallingConventions.obj	CallingConventionsTest

i.e. VS is looking for
	__declspec(dllexport) int __fastcall MyFastcall(int a, int b, int c);	

as `@MyFastcall@12` and cannot find it.
