### ISSUE TITLE
Source Code of Snuck.me

### ISSUE THREAD

**Issue by cs16lover** [JLospinoso/jlospinoso.github.io#3]
Hello Josh,

I've tried to find source code of snuck.me but no chance.

Where can I access source codes of Snuck.me project?

Thanks

P.S. Its written as "snuck.me is an open-source web service for querying an arbitrary site’s SSL certificate. " on your blog: https://jlospinoso.github.io/node/javascript/security/cryptography/privacy/2017/02/20/snuckme-cert-query.html

**Comment by JLospinoso** [comment]
Hi @cs16lover, thanks for the feedback!

The code is scattered through the blog post. I'll put it into a new repo later today to make it easier to set up your own.

Josh

**Comment by JLospinoso** [comment]
I've consolidated the relevant parts of the code here:

https://github.com/jlospinoso/snuckme

May be bugs to work through, please post a pull request :)
